spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./data/publicDB;AUTO_SERVER=TRUE
    username: admin
    password: admin


project:
  db:
    crypt:
      secret-key: ENC(oNDtJsaXi6uGOO31exIf/o6Sw11+Gr7qtqXtgZdaHMrf2h6soJK26pJL/qKcd+Vgmajkkn00v5AQ2WOmj6Ez2Nbd35SmvjW3r5jQd3YnZ/g=)
      iv: ENC(F4DWNzQrnDBTO7G5GiMROn3r6togyTOFiUuUTPDxJhWpzOMNCSdQUytmdfBThrgO6Ns0CweLX4LpbuU9TQpgzw==)